let tarsasJatek = [
    {
        nev: "Fedőnevek",
        kep: "../Pictures/Tarsas/fedonevek.png",
        id: 1,
        ar: 4500,
        leiras: "A Fedőnevek egy nagyon könnyen tanulható társasjáték, 2 - 8 játékos részére, az átlagos játékidő rövid, csak 15 perc. A játékot az Év Játékának választották 2016-ban (Spiel des Jahres) és jelölték is 2015-ben (BGG), illetve 2015-ben több, összesen 3 másik elismerést és jelölést is kapott. A társast, a könnyebb tanulhatósága ellenére, csak 14 éves kortól ajánljuk kipróbálni. A játékmenet erősen épít a szövetségek, a memória, a merj és nyerj és a limitált kommunikáció mechanizmusokra.",
        kedvelt: false
    },
    {
        nev: "Csordaszellem",
        kep: "../Pictures/Tarsas/csordaSzellem.png",
        id: 2,
        ar: 9000,
        leiras: "Köszöntünk a Csordaszellem világában! Ez nem csak egy sima társasjáték: ez egy izgalmas kaland, ahol a családod, barátaid és még a tehéncsordák is összegyűlnek a nagy összecsapásra.",
        kedvelt: true
    },
    {
        nev: "Dixit",
        kep: "../Pictures/Tarsas/dixit.png",
        id: 3,
        ar: 10000,
        leiras: "A határtalan képzelet játéka! A Dixit egy gyönyörűen illusztrált asszociációs játék, amellyel fantáziánkat szabadon engedve, újabb és újabb történeteket szőhetünk. Mindenki kap a kezébe hat darab nagyméretű kártyát, rajtuk festményekkel. A kezdőjátékos kiválaszt a kezében levők közül egyet, kitalál  hozzá egy mondatot, amely a képre jellemző, de mégsem túl  nyilvánvaló. Mindenki más is kiválaszt egy képet a kezéből, amelyre szerinte illik az adott mondat. Majd felfedjük  a lapokat, és a mesélőn kívül mindenki szavazhat, hogy  melyik képet választotta a mesélő. A Dixit egyike a legkedvelebb, legszórakoztatóbb társasjátékoknak, számtalan nemzetközi díj nyertese. Világszerte 1,5 milliónál is több példányt vásároltak belőle, ami nem lehet véletlen. Véleményünk szerint is az egyik legjobb társasjáték családok, baráti társaságok számára, de iskolák és más gyermekintézmények is gyakran választják készségfejlesztő és akár terápiás célokra.",
        kedvelt: false,
    },
    {
        nev: "Imagine",
        kep: "../Pictures/Tarsas/imagine.png",
        id: 4,
        ar: 7670,
        leiras: "Az Imagine egy zseniális ötleten alapuló, kreatív társasjáték. Engedd szabadjára a fantáziád: használj fel annyit és úgy a 60 átlátszó kártyából, hogy a többiek minél előbb kitalálják a helyes megoldást (filmek, helyek, szereplők...)! A kártyákat kedved szerint összeillesztheted, egymásra rakhatod, variálhatod és mozgathatod. Keltsd őket életre, és segíts a játékostársaidnak kitalálni, hogy mire gondolsz! A lehetőségek száma végtelen! Tedd próbára magad, nincsenek korlátok!",
        kedvelt: true,
    },
    {
        nev: "Truth or Drink",
        kep: "../Pictures/Tarsas/truthOrDrink.png",
        id: 5,
        ar: 7600,
        leiras: "Ismerd meg a Truth or Drink társasjátékot! Te döntesz: vagy bevallod a csupasz igazságot, vagy iszol egyet... de csak tisztán! Ez a játék garantálja, hogy az este végére szorosabbá válnak a barátságok, hiszen olyan titkok kerülnek napfényre, amelyekről korábban még csak nem is álmodtál.", 
        kedvelt: false,
    },
    {
        nev: "Bűnügyi krónikák",
        kep: "../Pictures/Tarsas/bunugyiKronikak.png",
        id: 6,
        ar: 14560,
        leiras: "Kedves Játékos! London, napjainkban. Gondterhelten lépsz ki a főnök irodájából az őrsön. Egy holttestet találtak a Hyde Parkban, és a kapitány neked adta az ügyet. Nem ez lesz az első nyomozásod, valahogy mégis rossz előérzeted támad az üggyel kapcsolatban... Lerázod magadról a baljós hangulatot, beszállsz a kocsiba, és elindulsz a tett helyszínére.",
        kedvelt: false,
    },
    {
        nev: "Az őszinteség játéka",
        kep: "../Pictures/Tarsas/ozintesegJateka.png",
        id: 7,
        ar: 8540,
        leiras: "A Körvonal kártyajáték egy remek módja annak, hogy jobban megismerjük egymást és önmagunkat. Nincsenek jó vagy rossz válaszok, csak az őszinteség és a közös beszélgetés a fontos. Legalább ketten játszható, de előfordulhat, hogy egy idő után már csak beszélgetünk, mert annyira jól érezzük magunkat.",
        kedvelt: false,
    },
    {
        nev: "Activity Original",
        kep: "../Pictures/Tarsas/activityOriginal.png",
        id: 8,
        ar: 13570,
        leiras: "Az Activity Original társasjáték a Piatniktól pontosan ezért jött létre. Ez a játék, ahol mindenki nyertes – kivéve, aki nem vesz részt benne! Úgyhogy csatlakozz te is a szórakozásra vágyók táborához és fedezd fel, hogy a nevetés valóban a legjobb gyógymód.",
        kedvelt: false, 
    },
    {
        nev: "Activity Felnőtt",
        kep: "../Pictures/Tarsas/activityFelnott.png",
        id: 9,
        ar: 17650,
        leiras: "Megújult szabályok, új erotikus feladványok és szleng kifejezések! Izgalmat fokozó időmérő és érdekes játékfelület! élre a gátlásokkal Hölgyek, Urak és máris indulhat az Activity sikerjáték, erotikus feladványokkal tűzdelt változata, hogy csúcsára érjen a bulin a hangulat!",
        kedvelt: true,
    },
    {
        nev: "Elvarázsolt Labirintus",
        kep: "../Pictures/Tarsas/elvarazsoltLabirintus.png",
        id: 10,
        ar: 9999,
        leiras: "Nagycsoportos ovis gyerekeknek tervezett sikerjáték Dirk Baumanntól, mely 2009-ben Az Év Gyerekjátéka díjat is elnyerte. Kis varázslótanoncokként próbáljuk összegyűjteni a varázstárgyakat egy különleges, elvarázsolt labirintusban. Nemcsak szerencse, hanem jó memória is szükséges a győzelemhez, ugyanis az útvesztő falai láthatatlanok! A kétrétegű játéktábla alsó felén variálható labirintusrendszert építhetünk falapocskákból. A mágneses bábuk alsó részéhez fémgolyó illeszkedik, mely a követi a bábu mozgását, míg falba nem ütközik. Aki nyerni akar, annak bizony meg kell jegyeznie, hogy hol vannak a labirintus falai.",
        kedvelt: false
    },
    {
        nev: "Légi társaság",
        kep: "../Pictures/Tarsas/legiTarsasag.png",
        id: 11,
        ar: 7999,
        leiras: "Vezérleld az utasszállító repülőgépet a megbízható társaddal, tökéletesen hangolva az erőfeszítéseket, és szállítsátok le az utasokat a világ minden táján. Csak egy kis együttműködésre és acélidegekre van szükség a sikerhez. bben a kooperatív társasjátékban egy csapatként, pilótákat alakítva kell a világ különböző repülőterein landolnotok. De egy repülőgéppel leszállni korántsem olyan egyszerű feladat, mint ahogyan azt elsőre gondolnánk. Kommunikálnotok kell az irányítótoronnyal, hogy megbizonyosodjatok róla, hogy biztonságosan megközelíthetitek a leszállópályát. Az előkészületek nagyon fontosak: az összes elemet el kell távolítani a vezérlőpultból és össze kell ragasztani a kétoldalas ragasztólapokat a vezérlőpult belsejében és hátulján. Rakhatsz a fordulásjelző-korong helyére és a kapcsolókat a zöld lámpákra.",
        kedvelt: false,
    },
    {
        nev: "Kuruzsló és Tsa. - Quedlinburgi Futam",
        kep: "../Pictures/Tarsas/quedlinburgiFutam.png",
        id: 12,
        ar: 5890,
        leiras: "A verseny napja van Quedlinburgban, és az ételek és a szerencse megfelelő kombinációjával győzelemre lovagolhatsz a lovaddal, és elnyerheted az arany üstöt. A Kuruzsló és Tsa. - Quedlinburgi Futam hasonló játékmenettel rendelkezik, mint a Kuruzslók Quedlinburgban a játék során minden játékos saját zsetonzsákot épít, majd ezeket a zsetonokat húzza, hogy megpróbáljon továbbjutni a győzelemhez.",
        kedvelt: false,
    },
    {
        nev: "Mycelia",
        kep: "../Pictures/Tarsas/mycelia.png",
        id: 13,
        ar: 16990,
        leiras: "Az avarban, ahová az ember tekintete gyakran nem ér el, a gombák királysága virágzik. Kapcsolódj be te is ebbe az örök körforgásba, légy részese a mindent összekötő hálózatnak – ki tudod használni a gombáid adta minden erőt, hogy magad mögé utasítsd az ellenfeleidet ebben a kíméletlen versenyben? A Mycelia egy dinamikus taktikai játék, amelyben a gombakirályságod létrehozásáért és területért folytatott versenyben vehetsz részt. A játék követi a gombák életciklusát: teremtés, terjeszkedés, pusztulás és újjászületés. A játék során pontokat gyűjtesz gombák növesztésével, spórákat szórsz szét a hálózatod bővítéséhez, és a gombák elpusztulásával különleges akciókat oldasz fel.",
        kedvelt: true,
    },
    {
        nev: "A sárkánybarlang rejtélye",
        kep: "../Pictures/Tarsas/sarkanyBarlangRejtelye.png",
        id: 14,
        ar: 6000,
        leiras: "Fedezd fel a sárkányok elrejtett kincseit, de vigyázz, nehogy a pókok hálójába ess! Most nagyon csendben kell lennetek, ha ép bőrrel meg akarjátok úszni a kalandot a sárkány barlangjába! Apró lépésekkel haladtok és igyekeztek gyémántot és különböző kincseket begyűjteni. De emlékeztek rá, hogy mit merre láttatok? Legyetek bátrak, kaparintsátok meg a kincseket, és a dicsőség nem marad el! Ha szeretnél egy izgalmas, kalandokkal teli játékot, amit az egész család élvezhet, akkor ne habozz! Szerezd be most A sárkánybarlang rejtélye társasjátékot, és kezdődhet a kaland!",
        kedvelt: true,
    },
    {
        nev: "Hygge",
        kep: "../Pictures/Tarsas/hygge.png",
        id: 15,
        ar: 3590,
        leiras: "Itt az ideje a téli álomnak, de a lakásodra ráfér egy kis munka, hogy igazán tökéletes legyen a nagy hidegre. Válogass okosan, kérd meg a megfelelő állatokat, hogy segítsenek, és garantáltan Tiéd lesz a legkellemesebb kis odú széles e vidéken. Ma buli van! De mindenki cucca szanaszét hever a házban, így mielőtt megérkeznének a vendégek, rendet kell rakni. Nagyi és Nagypapa is besegít, de a vendégek bármikor betoppanhatnak. Próbálj meg gyorsabban rendet rakni, mint bárki más. Tud minden családtag rendet rakni és fogadni a vendégeket baleset nélkül?",
        kedvelt: false,
    },
    {
        nev: "Melyik történetből jöttem?",
        kep: "../Pictures/Tarsas/melyikTortenetbolJottem.png",
        id: 16,
        ar: 5400,
        leiras: "Képes vagy felismerni, melyik bibliai történetre utalunk? Játssz activity-stílusban, mutogatva vagy akár szavak nélkül mesélve! Vajon újra tudod építeni a történetet a kulcsszavak alapján? Megtalálod-e a Biblia lapjain a történet nyomait? Ez a játék próbára teszi a tudásod és kreativitásod, ahogy a szónyomok alapján megpróbálod kitalálni az eredeti történetet. A játék 144 kártyát tartalmaz, melyekből 72 az ószövetségi, 72 pedig az újszövetségi történetekhez kapcsolódik. Minden kártyán 9 szó vagy kifejezés található, három különböző nehézségi szint szerint elrendezve. Ezekkel a szavakkal sokféle játékot játszhatsz: kitalálós, történetépítő, történetmesélő és történetnyomozó játékokat. A játék ideális hittanórákra is, hiszen rengeteg javaslatot tartalmaz erre vonatkozóan.",
        kedvelt: false
    },
];
// TÁRSASJÁTÉK VÉGE
let elektronikusJatek = [
    {
        nev: "Little lives pets: Mangó",
        kep: "../Pictures/Elektronikus/interaktivMaki.png",
        id: 17,
        ar: 21999,
        leiras: "Ismerd meg Mangót, a legaranyosabb kis interaktív maki babát, aki hamar a gyerekek legjobb barátjává válik! A Little Live Pets: Mangó, az interaktív maki babám egy igazán szeretnivaló, puha plüssfigura, amely valósághű viselkedésével hódítja meg a szíveket. Mangó több mint 70 különböző hangot és mozdulatot képes produkálni, így igazi társ a játékban. Ha a szájába helyezed az ujjadat, szopizni kezd, és boldogan csücsül az öledben. Emellett etetheted a hozzá tartozó cumisüvegből is, ami után elégedetten gügyög és boldogan mocorog.",
        kedvelt: false,
    },
    {
        nev: "Furby",
        kep: "../Pictures/Elektronikus/furbyInteraktiv.png",
        id: 18,
        ar: 19999,
        leiras: "A népszerű Furby nem csak egy hagyományos plüssfigura, hanem annál sokkal több! A Furby-k mindegyike külön személyiséggel rendelkezik, ennek köszönhetően más és más reakciókat produkálnak. De vajon a Te Furby-d milyen személyiséget sajátít el? Minden azon múlik, hogyan játszol és foglalkozol vele! A kis lila szőrmók minden egyes megmozdulásodra reagál, így akár etetheted, felemelheted, rázhatod, megfordíthatod vagy zenét játszhatsz le neki, mindenre reagálni fog!",
        kedvelt: false,
    },
    {
        nev: "Tamagocsi",
        kep: "../Pictures/Elektronikus/pocketPet.png",
        id: 19,
        ar: 1999,
        leiras: "Ismét hódít a 90-es évek játék szenzációja, a Tamagotchi! Válaszd ki a 168 féle kisállat közül a kedvencedet, majd gondoskodj róla a kis gombok segítségével, etesd meg, játssz vele, altasd el, gyógyítsd meg, ha beteg, takaríts fel utána, de akár le is zárhatod, hogy senki ne nyúlhasson hozzá!",
        kedvelt: true,
    },
    {
        nev: "Verd át a kamerát",
        kep: "../Pictures/Elektronikus/verdAtAKamerat.png",
        id: 20,
        ar: 12999,
        leiras: "A Tomy 'Verd át a kamerát' társasjáték egy izgalmas ügyességi próba, ahol a cél a drágakő megszerzése, miközben egy mozgásérzékelős kamera próbálja elkapni a játékosokat. Egyszerűen helyezze el a dobozban lévő éberszemű kamerát egy asztalon vagy bármilyen más stabil felületen, rejtsd el a kincset, és kezdődhet az izgalom.",
        kedvelt: false,
    },
    {
        nev: "Szuper Mágikus Jinn",
        kep: "../Pictures/Elektronikus/magikusJinn.png",
        id: 21,
        ar: 11995,
        leiras: "Sziasztok! Szuper Mágikus Jinn vagyok!\\\\ Ez a mókás figura mindig így köszön, és bármikor szívesen játszik a gyerekekkel: méghozzá barkochbát. Csak gondolni kell egy állatra, ruhadarabra, zöldségre vagy gyümölcsre, sportágra vagy foglalkozása, Szuper Mágikus Jinn kitalálja azt! Ez az interaktív lényecske eldöntendő kérdéseket tesz fel, hangfelismerő rendszerének köszönhetően pedig a gyerekek szóban válaszolhatnak, így tulajdonképpen beszélgetnek Jinnel. Igen, nem, nem tudom, attól függ... Ahogy megválaszolják a kérdéseket, Jinn egyre közelebb kerül a megfejtéshez. Remekül leköti a már nagyobb óvodás gyerekeket - sőt, akár a szülőket - is, kompakt mérete miatt pedig utazáshoz is ideális társ. A játék remekül fejleszti a logikus gondolkodást, miközben a gyerekek jól szórakoznak.",
        kedvelt: true,
    },
    {
        nev: "Bitzee",
        kep: "../Pictures/Elektronikus/bitzeeInteraktiv.png",
        id: 22,
        ar: 19990,
        leiras: "Fedezd fel a Disney varázslatos világát a Bitzee Interaktív digitális állat Disney kiadással! Ez az innovatív játék a klasszikus tamagotchi élményt ötvözi a legújabb technológiával, hogy a gyermeked elmerülhessen a Disney karakterek gondozásában és játékában. A Bitzee egy kicsi, hordozható eszköz, melyben 30 különböző Disney karaktert lehet felfedezni, beleértve Mickey egér, Minnie egér, és még sok más népszerű figurát. A gyerekeknek lehetőségük van etetni, gondozni, és játszani ezekkel a digitális barátokkal, miközben különböző kihívásokat és játékokat oldanak meg. A színes kijelző és az interaktív funkciók révén a Bitzee minden pillanatban új élményeket kínál, a gyermekek figyelmét lekötve és kreativitásukat fejlesztve.",
        kedvelt: false,
    },
    {
        nev: "Tacsi robotkutya",
        kep: "../Pictures/Elektronikus/robotKutya.png",
        id: 23,
        ar: 34999,
        leiras: "A kutya az ember legjobb barátja, különösen ha ez a kutya egy robot, hiszen akkor biztos, hogy a gazdi minden parancsát teljesíti! A Tacsi kutyus nagyon cuki, szófogadó és sokat szeret játszani, így ideális játszópajtása lesz a gyerekeknek. Mindenhova követi őket és figyeli minden apró mozdulatukat. Tacsi hangokat képes kiadni, csóválja a farkát vagy épp szaglászik valami után akárcsak egy igazi kutya, de természetesen különféle trükköket is előadhattok közösen. A labdájával lehet irányítani, kétféle funkciót kiválasztva. A követő módban az árnyékok és mozgások segítségével tájékozódik, mint egy valódi kutyus, míg a kézi vezérlés módot bekapcsolva pedig a labdán lévő gombok segítségével lehet vezérelni.",
        kedvelt: true,
    },
    {
        nev: "Táncoló kaktusz",
        kep: "../Pictures/Elektronikus/tancoloKaktusz.png",
        id: 24,
        ar: 10999,
        leiras: "A legtöbb gyerekszobában nem igen vannak növények, hiszen a rendszeres locsolás elmaradása nem tesz túl jót nekik, de most itt a nagyszerű lehetőség, hogy egy mókás kaktusz azért helyet kapjon a polcon vagy éppen az íróasztal egyik sarkán. Ez a kaktusz nem éppen hétköznapi figura, hiszen a benne rejlő elektronikának és a három darab AAA ceruzaelemnek köszönhetően mókás zenével és vicces tánccal tudja szórakoztatni a gyerekeket, ráadásul attól sem kell félni, hogy bárkit megszúrna, hiszen ez egy igazán kedves kaktusz.",
        kedvelt: false,
    },
    {
        nev: "LG Kizon W105",
        kep: "../Pictures/Elektronikus/kizon.png",
        id: 25,
        ar: 4999,
        leiras: "Az LG KizON okoskarpánt GPS és csak a helymeghatározás céljából működő WiFi segítségével mindig segít tájékozódni gyermeke pontos tartózkodási helyéről. A karpánt segítségével, gyermeke egyetlen gombnyomással bármikor aktiválni tud egy előre betáplált telefonszámot. Abban az esetben, ha gyermeke nem reagál a hívásra, egy bizonyos idő után automatikusan aktiválódik a készülék beépített mikrofonja. Ezáltal hallható lesz gyermeke hangja és a környezet zaja.",
        kedvelt: false,
    },
    {
        nev: "ZR Walkie Talkie",
        kep: "../Pictures/Elektronikus/walkieTalkie.png",
        id: 26,
        ar: 4499,
        leiras: "Ez a vagány kültéri Walkie Talkie antennával ideális választás a fiatal felfedezők számára. A menő burkolattal ellátott készülékkel a gyerekek jócskán eltávolodhatnak egymástól, hiszen a készülék több méteres hatótávolsággal is képes működni a szabadban. Használat közben nem szabad elfelejteni, hogy el azonos sávon kell használni mindkét készüléket, és ennék a készüléknél is igaz, hogy vagy beszélünk vagy hallgatunk, így amikor végeztél a mondandóddal ne felejtsük el azt mondani, hogy VÉTEL!! ",
        kedvelt: false,
    },
    {
        nev: "Star Wars Lightsaber Forge: Darksaber",
        kep: "../Pictures/Elektronikus/fenykard.png",
        id: 27,
        ar: 9999,
        leiras: "A Star Wars Lightsaber Forge: Darksaber kinyitható elektronikus fénykard tökéletes választás a Star Wars világának rajongói számára, akik szeretnék a Mandalori örökség egyik legikonikusabb fegyverét a kezükben tartani. A Darksaber nemcsak egy fénykard, hanem a galaxis egyik legkülönlegesebb, fekete pengéjű fegyvere, amelyet Mandalore uralkodói használtak. Most te is csatlakozhatsz ehhez a legendás hagyományhoz ezzel a valósághű fény- és hanghatásokkal felszerelt játékkal.",
        kedvelt: true,
    },
    {
        nev: "Óriás zongora",
        kep: "../Pictures/Elektronikus/zongora.png",
        id: 28,
        ar: 17999,
        leiras: "Játszd el kedvenc zenéidet a hatalamas méretű zongorán! A Zongora óriás játszószőnyeg egy nyomásérzékelős billentyűzet, két oktávval. A zongorán lépkedve tudsz játszani, a játék 8 hangszer hangját tudja utánozni, négy beépített dalt is le tud játszani. A szőnyeg hangereje állítható, a művedet fel tudod vele venni, és vissza is tudod hallgatni! A Zongora óriás játszószőnyeg 4 darab AA ceruzaelemmel működik, a csomagolás az elemeket nem tartalmazza.",
        kedvelt: false,
    },
    {
        nev: "Játék mobiltelefon",
        kep: "../Pictures/Elektronikus/jatekTelefon.png",
        id: 29,
        ar: 1999,
        leiras: "Gyakorold a telefonálást a szétcsúsztatható játéktelefonnal! A Játék mobiltelefon egy élethű mobiltelefon, ami fejleszti a kommunikációs készséget. A telefon fedőlapja elcsúsztatható, a gombok megnyomására a játék különböző mondatokat, hangokat ad ki magából. A telefon kijelzője hologramos, több irányból nézve más-más kép jelenik meg rajta. A Játék mobiltelefon 2 db LR44 gombelemmel működik, a csomagolás az elemeket tartalmazza. A telefon összecsukott méretei: 10 x 5 x 2 cm. A termék fekete, bordó és világoskék színben kapható. A játékok külön kaphatóak. A megjegyzésben kérjük tüntesd fel, hogy melyik változatot szeretnéd!",
        kedvelt: false,
    },
    {
        nev: "Első laptopom",
        kep: "../Pictures/Elektronikus/elsoLaptopom.png",
        id: 30,
        ar: 8799,
        leiras: "Nyiss kaput a szórakoztatásra! A gyermeklaptopunkban 33 különböző tevékenységet találsz. Tanulhatod a betűket, a számokat és a szavakat, valamint zenélhetsz és játékokkal játszhatsz. Imádni fogod, ahogy az egérrel mozoghatsz a képernyőn. Pont olyan, mint az igazi! 3 éves kortól ajánlott. Hat választható működési mód. Olvasási-írási készségek. Problémamegoldás. Próbálj ki! Kezelési útmutató: Tisztítás csak törléssel.",
        kedvelt: true,
    },
    {
        nev: "Bobby kutyus",
        kep: "../Pictures/Elektronikus/bobbyKutyus.png",
        id: 31,
        ar: 7999,
        leiras: "Minden gyerek életében eljön a pillanat amikor bejelentik: \"Anyaaaa, úúúúgy szeretnék egy kutyát!\" A felelős állattartásra fel kell készíteni a gyerekeket, ez a sétáltatható plüss kiskutya pedig nagyszerű első lépés az óvodáskorú gyerekek számára, hiszen megtanulhatják, hogyan kell gondoskodni egy igazi állatról. A kutyus szuper cuki, és különböző funkciókkal is rendelkezik. Csak fel kell tolni a pórázon található pöcköt, hogy az eb ugatni kezdjen és csóválja a farkát séta közben.",
        kedvelt: false,
    },
    {
        nev: "Dance Revolution Táncszönyeg",
        kep: "../Pictures/Elektronikus/tancSzonyeg.png",
        id: 32,
        ar: 9990,
        leiras: "Most lehet csak igazán jót táncolni és ugrálni, ideje megmutatni, ki mit tud! A Dance Revolution táncszőnyeg TV-re és PC-re csatlakoztatható, és egy igazán remek szórakozás a gyerekeknek! A hiperaktív gyerkőcök kedvükre mozoghatnak, miközben fejlődnek a reflexeik és a ritmusérzékük. Az ifjú táncosoknak a TV-n vagy a számítógép monitorán megjelenő nyilakat követve kell megismételniük a lépéseket. Akinek több helyes lépése lesz, az nyeri a nagy táncpárbajt. A gyerekek összesen 48 dal és 2 játék közül választhatnak.A táncszőnyeg TV-hez RCA csatlakozóval, PC-re USB csatlakozóval köthető. A táncszőnyeg kizárólag az RCA (kompozit A/V) csatlakozóval rendelkező TV-re köthető. A táncszőnyeg működése nem igényel külön elemeket.A csomagolás tartalmaz egy táncszőnyeget, egy CD-t, a csatlakoztatáshoz szükséges kábeleket, valamint egy adaptert.",
        kedvelt: false,
    },
];
// ELEKTRONIKUSJÁTÉK VÉGE
let jatekFegyverek = [
    {
        nev: "Nerf Minecraft Ender Dragon",
        kep: "../Pictures/Jatekfegyverek/minecraftEnder.png",
        id: 33,
        ar: 9999,
        leiras: "A nerfmarket.hu webáruházban a NERF játékosok számára készült gyermekpisztolyok, dartsok és golyók legnagyobb választékát találja. A legtöbb áru raktáron. Márkák: NERF Rival, NERF Modulus, NERF Elite, NERF N-Strike, NERF Zombie Strike, X-Shot, TACK PRO. Kiegészítők nagy választéka: Eredeti NERF kiegészítők, WORKER, rugók, nyilak, golyók, NERF tuning, NERF módosítások.",
        kedvelt: false,
    },
    {
        nev: "Nerf Minecraft Sabrewing",
        kep: "../Pictures/Jatekfegyverek/minecraftSabrewing.png",
        id: 34,
        ar: 24999,
        leiras: "Az íj szabályos Elit nyilakat lő ki. Az íj egy speciális tárral rendelkezik 8 nyílvessző számára, amely az íjtest igényeire lett kialakítva, és az egyik oldaláról (konkrétan a felső felében) van behelyezve. Különleges formája miatt a tár nem kompatibilis más blasterek más táraival, pedig szabványos Elite dartshoz készült. A tár csak ehhez a blasterhez készült. Maga a lövöldözés úgy történik, hogy a játékos meghúzza a zsinórt, ami aktiválja a robbanómotort. Ezt követően a blaster közepén lévő ravasz minden egyes megnyomása egy nyílvesszőt lő ki. Így ahhoz, hogy a robbantó tüzeljen, meg kell feszíteni a húrt, és egyidejűleg meg kell nyomni a robbantó közepén lévő gombot.",
        kedvelt: true,
    },
    {
        nev: "Nerf Microshot Minecraft Ghast",
        kep: "../Pictures/Jatekfegyverek/minecraftGhast.png",
        id: 35,
        ar: 4899,
        leiras: "Egy kis egynyíl kézi pisztoly, amely a MINECRAFT játék készítőivel együttműködésben készült. Beletöltődik a hordóba, manuálisan megnyújtja és elsüti. A csomag két ELITE nyilat tartalmaz. A MICROSHOTS egy gyűjtői sorozat, amely a legnépszerűbb NERF pisztolyokat vagy a legnépszerűbb fegyvereket játékokból alakítja át kis JOLT pisztolyokká. A pisztolyok különféle formákban kaphatók. A népszerű számítógépes játékok fegyvereitől az őrült tárgyakon át a klasszikus NERF pisztolyok kicsinyített változataiig. Ezek a termékek nagyon keresettek a rajongók és a gyűjtők körében egyaránt. A MICROSHOTS kézi pisztolyok egy nyíl kapacitással és teljesen kompatibilisek az ELITE nyilakkal. Viszonylag alacsony ára is előnyös.",
        kedvelt: false,
    },
    {
        nev: "Nerf SS Hydro Frenzy",
        kep: "../Pictures/Jatekfegyverek/nerfSS.png",
        id: 36,
        ar: 8599,
        leiras: "A Nerf Hydro Frenzy 2 csővel rendelkezik a főben. A cső permetezés közben forog, és minden irányban vízsugarat bocsát ki. A szivattyúzással a kamrát levegővel nyomás alá helyezik. A ravaszt megnyomva két folyamatos vízsugár szabadul fel. A víz feltöltése a kupak kinyitása után történik. Ezután csak nyomja meg a fogantyút, hogy nyomás alá kerüljön, majd nyomja meg a ravaszt. Ez a típusú Super Soaker három vízpermetezési móddal rendelkezik. Attól függően, hogy a narancssárga kupak hogyan van elfordítva a hordónál, a víz akár egyenesen, akár oldalra, vagy véletlenszerűen \"őrülten\" csoboghat körülötted.",
        kedvelt: false,
    },
    {
        nev: "Nerf Microshot Fortnite Thunder Crash",
        kep: "../Pictures/Jatekfegyverek/fortniteThunder.png",
        id: 37,
        ar: 4999,
        leiras: "Egy kis egynyíl kézi pisztoly, amely a FORTNITE játék készítőivel együttműködésben készült. A limitált kiadású NERF MICROSHOT FORTNITE ELITE nyilak része. Beletöltődik a hordóba, manuálisan nyújtja és tüzel. A csomag két ELITE nyilat tartalmaz a FORTNITE kivitelben. A NERF robbantók olyan lövedékeket lőnek ki, amelyek torkolati sebessége 50-100 FPS a robbantó típusától függően. Ezért játék közben védened kell a szemed! SOHA NE játsszon Nerfet megfelelő szemvédelem nélkül, mert a védetlen szemet eltaláló lövedékek súlyos szemsérülést vagy látásvesztést okozhatnak!",
        kedvelt: true,
    },
    {
        nev: "Nerf Dinosquad - Rex-Rampage",
        kep: "../Pictures/Jatekfegyverek/dinoSquad.png",
        id: 38,
        ar: 20999,
        leiras: "A megjelenést a Tyrannosaur REX ihlette. A REX-RAMPAGE ELIT nyilakat lő. Egy kivehető 10 nyílból álló íves tárral tölthető. A tartályok kompatibilisek a CLIP rendszerrel és cserélhetők. Beépített viszonylag masszív készlettel rendelkezik, amely nyíltartókat tartalmaz. A fő felett egy integrált (fix) irányzék található. Ez egy elektromos pisztoly, így működéséhez 4 x 1,5 V AA elem szükséges (nem tartozék). A NERF DINOSQUAD egy olyan kiadás, amely tematikusan a dinoszauruszokra összpontosít. Minden pisztoly egy dinoszauruszfajtának van beállítva (pl. REX, TRICERA stb.). A kiadás kézi és elektromos pisztolyokat is tartalmaz magazinokhoz. Az ebből a kiadásból származó termékek szabványos ELITE nyilakat használnak.",
        kedvelt: false,
    },
    {
        nev: "Nerf Dinosquad - Stego-Smash",
        kep: "../Pictures/Jatekfegyverek/stegosmash.png",
        id: 39,
        ar: 5499,
        leiras: "A NERF DINOSQUAD - STEGOSMASH egy kézi pisztoly a DINOSQUAD kiadásból. A megjelenést a Stegosaurus dinoszaurusz ihlette. Ez egy egyszerű egynyíl pisztoly. Közvetlenül a hordóba töltődik. A fő elöl alatt egy tartó található 4 nyíl számára. Kézi pisztolyról van szó, így működéséhez nincs szükség elemre.",
        kedvelt: true,
    },
    {
        nev: "NERF ROBLOX NINJA LEGENDS SHADOW SENSEI",
        kep: "../Pictures/Jatekfegyverek/shadowSensei.png",
        id: 40,
        ar: 15999,
        leiras: "A NERF ROBLOX NINJA LEGENDS SHADOW SENSEI egy közepes méretű pumpás puska a ROBLOX sorozatból. Ez egy kézi szivattyús robbantó. 6 fő van benne. Közvetlenül a hordóba töltik. Klasszikus ELITE típusú nyilakkal működik. Sorsolásonként egy nyilat lő ki. A hordó alatti pumpálással nyújtják. A csomag tartalmaz egy ROBLOX játék aktiváló kódot, amellyel egy exkluzív virtuális tárgyat válthatsz be a játékban.",
        kedvelt: false,
    },
    {
        nev: "NERF HALO - MA40",
        kep: "../Pictures/Jatekfegyverek/nerfHalo.png",
        id: 41,
        ar: 18999,
        leiras: "A NERF HALO - MA40 egy elektromos félautomata sugárzó a NERF HALO sorozatból. A HALO: Infinite játék ihlette. Ez egy elektromos félautomata pisztoly. Ez azt jelenti, hogy a ravasz alatt van egy második gomb, amely aktiválja a motort, és a ravasz minden megnyomásakor kilő egy nyilat. Következő megnyomás, majd újabb nyíl fog kilőni stb.  A működéshez 4 db C 1,5 V-os elem szükséges (az elemeket nem tartalmazza). A 10 nyíl kapacitású CLIP SYSTEM tárba tölthető. Működik a klasszikus Elite nyilakkal. A tetején egy rövid taktikai sín található a tartozékok csatlakoztatásához. A szállítás tartalmaz egy hosszabbítót a taktikai sín (sín) megemelésére és egy \"oszcilloszkópot\" (felülről a taktikai sínre csatlakoztatható oszcilloszkóp modell).",
        kedvelt: false,
    },
    {
        nev: "Hátra akasztható vízipuska",
        kep: "../Pictures/Jatekfegyverek/vizipisztoly26.png",
        id: 42,
        ar: 5495,
        leiras: "A vízparti nyaralások és medencés bulik kötelező kelléke. Strapabíró műanyagból készült, csak fel kell tölteni a tartályokat vízzel, majd hátizsákként a gyermek hátára helyezni.",
        kedvelt: false,
    },
    {
        nev: "Tartályos vízipisztoly - 26 cm, többféle",
        kep: "../Pictures/Jatekfegyverek/viziPuska.png",
        id: 43,
        ar: 995,
        leiras: "Hűtsd le a kedélyeket a tartályos vízipisztollyal! A Tartályos vízipisztoly egy műanyagból készült, pumpás rendszerű vízifegyver, amivel senki sem ússza meg szárazon, ha eltalálod! A tartályt először töltsd fel vízzel, majd csavard be a helyére, utána már csak a pumpával kell nyomás alá helyezni a vizet. Amikor meghúzod a ravaszt, a víz erős sugárban fog kilőni, és ezzel bárkit eláztathatsz pillanatok alatt! A Tartályos vízipisztoly strandon és tóparton is használható. Méret: 26 cm. A játékok külön kaphatóak. A megjegyzésben kérjük tüntesd fel, hogy melyik változatot szeretnéd!",
        kedvelt: true,
    },
    {
        nev: "Pumpás vízipisztoly 58 cm",
        kep: "../Pictures/Jatekfegyverek/vizipisztoly56.png",
        id: 44,
        ar: 2995,
        leiras: "A strandon és a nyári melegben minden apró lurkónak kötelező alapfelszerelés egy jó vízipisztoly. Fürdőzések és strandolások alkalmával igazán felejthetetlen és vicces pillanatokat okozhatsz most. Játszatok együtt barátaiddal és harcoljatok úgy, mint még soha. A vízipisztoly mérete: 58 cm.",
        kedvelt: false,
    },
    {
        nev: "Vízipisztoly dupla csővel - 49 cm",
        kep: "../Pictures/Jatekfegyverek/vizipisztoly23757.png",
        id: 45,
        ar: 2495,
        leiras: "Hűsítsd le barátaidat játszva! Nem is tehetnél jobbat velük a nyári forróságban: kergessétek egymást és versenyezzetek, hogy ki tudja a másikat többször lespriccelni vízzel. Irány a strand, vagy a park, és élvezzétek az iskolai szünetet ezzel a dupla lövetű vízipisztollyal. A játék mérete: 49 cm hosszú. A terméket 3 éves kortól ajánljuk.",
        kedvelt: false,
    },
    {
        nev: "Vízipisztoly - 4 darabos",
        kep: "../Pictures/Jatekfegyverek/darabosVizi.png",
        id: 46,
        ar: 995,
        leiras: "Készülj fel a nyári kalandokra ezzel a szuper strandeszközzel! A Vízipisztolyos készlettel végre 4 darab, különböző neon színű, spriccelő fegyverhez juthatsz hozzá. Válaszd hát ezt a csomagot, és vidd magaddal a partra, hogy barátaiddal versenyezve hűsíthesd le magad a forró napsütésben! A Vízipisztoly csomagolásának méretei: 28 x 12 x 2 cm. A játékot 3 éves kortól ajánljuk.",
        kedvelt: true,
    },
    {
        nev: "Silverlit HydroM. A. D elektromos vízip. kék",
        kep: "../Pictures/Jatekfegyverek/hydroElektro.png",
        id: 47,
        ar: 9995,
        leiras: "Emeljétek új szintre a vízi csatákat! A Hydro M.A.D. elektromos vízipisztollyal a gyerekek őrült csatákat vívhatnak a nyári kánikulában akár a kertben, akár a vízparton. Csak meg kell tölteni, aztán meghúzni a ravaszt, és a vízsugár akár 10 méter távolságba is kilő. Egy töltettel több, mint 450 lövés adható le.",
        kedvelt: false,
    },
    {
        nev: "Katonai vízipisztoly 50 cm",
        kep: "../Pictures/Jatekfegyverek/katonaiVizipisztoly.png",
        id: 48,
        ar: 2995,
        leiras: "Legyél te a vízicsaték királya ezzel az 50 centiméteres vízipisztollyal. A pisztoly garantálja a fergeteges szórakozást a nyári napokon. Magaddal viheted a strandra, a tengerpartra, de akár egy nyári szülinapi partinak is mókás kiegészítője lehet. Csak töltsd meg a tartályt vízzel és már indulhat is a játék.",
        kedvelt: true,
    },
]
// JÁTÉKFEGYVEREK VÉGE
let muanyag = [
    {
        nev: "McLaren P1",
        kep: "../Pictures/Muanyag/mcLaren.png",
        id: 49,
        ar: 99000,
        leiras: "„A levegő sima, kanyargó, organikus görbék mentén szeret mozogni, és a biomimetikából, valamint a hidro- és aerodinamikából ihletet merítve tanulmányoztuk pörölycápák és repülő sólymok képeit.\"",
        kedvelt: true,
    },
    {
        nev: "Egzotikus páva",
        kep: "../Pictures/Jatekfegyverek/pava.png",
        id: 50,
        ar: 6990,
        leiras: "A LEGO® Creator Egzotikus páva (31157) 3 az 1-ben szettel a 7 éves vagy nagyobb fiúk és lányok 3 különböző egzotikus LEGO® állatos játékot építhetnek meg, és játszhatnak is velük. Tartalmaz egy játék pávát, amelynek gyönyörű és részletgazdag farktollai összecsukhatók és kitárhatók. Ez a LEGO® Creator 3 az 1-ben készlet egy szett kockával nyújt 3 különböző építési és játékélményt a gyerekeknek. Építhetnek egy páva játékfigurát, majd átépíthetik egy játék szitakötővé, amelynek beállítható szárnya és farka van, és egy tavirózsa-állványon pihen, vagy egy színes játék pillangóvá, beállítható szárnyakkal. Mind a 3, játékra is alkalmas modell szép kiállítási darab lehet a polcon vagy az éjjeliszekrényen.",
        kedvelt: false,
    },
    {
        nev: "Mona Lisa",
        kep: "../Pictures/Jatekfegyverek/moneLisa.png",
        id: 51,
        ar: 42990,
        leiras: "Alkosd meg saját mesterművedet ezzel a LEGO® Art Mona Lisa (31213) festményt rejtő építőszettel! A műkedvelők egy magával ragadó, örömteli projektben merülhetnek el, miközben egyedül, vagy a barátaikkal összerakják Leonardo da Vinci műalkotásának merész és egyedi újragondolását. Ez a falra akasztható műalkotás remek ajándék lehet a számodra, de lakásdekorációs meglepetés is lehet férfiaknak, nőknek, műkedvelőknek. A kékebb árnyalat azokat a színeket próbálja megeleveníteni, amelyeket da Vinci használt 500 évvel ezelőtt, mielőtt a festék az évek múlásával megváltozott volna. A Mona Lisa híres tekintetét ábrázoló elemek sima, díszítés nélküli elemekre cserélhetők, hogy még elvontabb legyen a megjelenése.",
        kedvelt: true,
    },
    {
        nev: "Obi-Wan Kenobi™ és Darth Vader™",
        kep: "../Pictures/Jatekfegyverek/obiWan.png",
        id: 52,
        ar: 8990,
        leiras: "A rajongók újra átélhetik a Star Wars: Obi-Wan Kenobi című sorozat drámai jeleneteit, miközben megépítik Obi-Wan Kenobi és Darth Vader ikonikus szereplők LEGO® BrickHeadz változatait. Ezzel a párossal hatalmas az Erő – a hiteles részletek között megtalálod Darth Vader piros szemét és 1-1 fénykardot mindkét megépíthető LEGO® figurához. A kiállításhoz pedig bemutatóállványok is várnak rád. Ez a kreatív építőjáték remek 10 éves kortól, emellett bármelyik Star Wars™ rajongó gyűjteményének nagyszerű része lehet.",
        kedvelt: true,
    },
    {
        nev: "Pókember maszkja",
        kep: "../Pictures/Jatekfegyverek/pokember.png",
        id: 53,
        ar: 8990,
        leiras: "Ezzel a gyűjthető, LEGO® Marvel Pókember maszkja (76285) szettel a felnőtt Marvel-rajongók megmutathatják, mennyire imádják Pókembert. Ez a részletgazdag, megépíthető modell magán viseli a Marvel-moziuniverzum egyik legismertebb, ikonikus szuperhősének stílusát. A 487 elemből álló megépíthető modell 19 cm magas, és névtáblával ellátott, masszív állványon pihen. A kényelem kedvéért, a készlethez tartozó építési útmutató digitális változatát a LEGO Builder appban is megtalálod. A felnőtteknek szóló LEGO Marvel ajándékok választéka olyan igazán örömteli építési és kiállítási élményt nyújt, amely a megépítés után is sokáig velük marad.",
        kedvelt: false,
    },
    {
        nev: "Birodalmi csillagromboló™",
        kep: "../Pictures/Jatekfegyverek/starWars.png",
        id: 54,
        ar: 69990,
        leiras: "Urald a galaxist ezzel a LEGO® Star Wars™ Birodalmi csillagromboló™, megépíthető, gyermekeknek készült játékszettel (75394)! Szuper születésnapi ajándék 10+ éves fiúknak, lányoknak és rajongóknak, hiszen ezen a Star Wars csillaghajót tartalmazó építőjátékon van egy rejtett, kihajtható hordozófül a modell reptetéséhez, továbbá 2 rugós kilövővel van ellátva, a tetején lévő panel levehető, az oldalsó panelek pedig kinyithatók, hogy könnyen hozzá lehessen férni a részletgazdag belső térhez. A játékos belső elemek közt egy hidat, egy irányítótermet, egy pihenőszobát, egy fegyverraktárat, továbbá irányítópaneleket és hődetonátor-elemeket rejtő rakományt találsz.",
        kedvelt: false,
    },
    {
        nev: "Mordály & Baby Groot",
        kep: "../Pictures/Jatekfegyverek/babyGroot.png",
        id: 55,
        ar: 24990,
        leiras: "Emeled a Marvel-filmek akciójeleneteit egy új szintre a LEGO® Marvel Mordály és Baby Groot (76282) szettel! Ez a 10 éves kortól fiúknak és lányoknak egyaránt ajánlott, megépíthető játék csuklós, valósághűen részletgazdag és 22 cm magas. Ez a játék több, mint egy gyerekeknek készült építőjáték, hiszen a Marvel Studios A galaxis őrzői című film ikonikus szereplőjének valósághű mása. A beállítható, megépíthető modell tükrözi a szuperhős lázadó karakterét és fegyverimádatát. Mindegyik illesztés (a könyökök kivételével) mozgatható a maximális játék- és kiállítási élményért. A figura rugós kilövőt és pisztolyt tart a kezében. Vállán az édes kis barátja, Baby Groot ül. Ha egy vagány megépíthető játékot keresel kis szuperhősöknek, akkor a LEGO Marvel Mordály & Baby Groot tökéletes választás azoknak a gyerekeknek, akik meg akarják mutatni, mennyire szuper szuperhősök! Az extra digitális élményért pedig, az építők felnagyíthatják és elforgathatják a modellek 3D-s változatát, és követhetik a haladásukat a vidám és intuitív LEGO Builder appal.",
        kedvelt: true,
    },
    {
        nev: "A sütőtök farm",
        kep: "../Pictures/Jatekfegyverek/mc.png",
        id: 56,
        ar: 15990,
        leiras: "A Minecraft® játékosok a videójátékban megjelenő sütőtököket helyezhetik a középpontba a LEGO® Minecraft A sütőtök farm (21248) készlettel. A videójáték egyik legnépszerűbb karakterével és egy bajkeverő boszorkánnyal ez a játékszett végtelen, akciódús kalandot tartogat a sütőtök farmon a 8+ éves gyerekeknek. Ez a sokoldalúan alakítható játék a hírhedt mocsár biomban, a tök formájú ház körüli tökfarmon játszódik Steve-vel, az egyik főszereplővel. A ház be van rendezve, található benne egy ágy, egy barkácsasztal, egy kohó és egy békalámpa. Körülötte található a sütőtök farm, amelyet Steve művel meg a kapájával. A játéklehetőségek közt megjelenik a csatázás, amikor a boszorkány bájitalokat dobál Steve-re, aki az íjával hárítja a támadást. A szetthez tartozik egy béka, egy csónak és egy kincsesláda is, amely tojást és cukrot rejt, hogy a gyerekek sütőtökös pitét készíthessenek! A digitális élmény kedvéért az építők 3D-nézetben ráközelíthetnek és elforgathatják a szetteket, és követhetik az építés menetét a szórakoztató LEGO Builder appal.",
        kedvelt: false,
    },
    {
        nev: "Mega műanyag 350 darabos építőjáték",
        kep: "../Pictures/Jatekfegyverek/epitojatek.png",
        id: 57,
        ar: 3590,
        leiras: "Rakj össze szép építményeket, különleges formájú építőelemekből! A Mega műanyag 350 darabos építőjáték különleges formájú, piros, sárga, zöld, kék, fehér és fekete építőelemekből áll, amiket rengeteg módon tudsz összeakasztani. A kirakós játékból autókat, hajókat, házakat és kertet is össze tudsz rakni, a furcsa darabokból kocka formákat tudsz készíteni, de akár 45 fokban is illesztheted őket! A Mega műanyag 350 darabos építőjáték fejleszti a kreativitást, az összerakás fejleszti a kézügyességed is! Csomagolás méretei: 22 x 14 x 9 cm.",
        kedvelt: false,
    },
    {
        nev: "Ravensburger Puzzle 3x49 db - Minecraft Biomák",
        kep: "../Pictures/Jatekfegyverek/mcLego.png",
        id: 58,
        ar: 4495,
        leiras: "Puzzle 3x49 db - Minecraft Biomák 3 x 49 darabos Minecraft puzzle a Ravensburger márkától. A kirakó dobozában 3 darab kirakót rakhattok ki a Minecraft Biomokról. A kirakó, minőségi, kemény kartonpapírból készült, nagyon színes és tűéles képet ábrázol miután kiraktátok Ha gyermeked rajong a Minecraftos játékokért, lepd meg őt ezzel a 3 x 49 darabos kirakóval, melynek biztosan örülni fog",
        kedvelt: false,
    },
    {
        nev: "Ravensburger: Eiffel-torony 216 darabos 3D puzzle fénnyel",
        kep: "../Pictures/Jatekfegyverek/ejfelTorony.png",
        id: 59,
        ar: 14995,
        leiras: "Párizs legismertebb épülete, LED világítással, mozaikdarabokból! A Ravensburger Eiffel-torony 216 darabos 3D puzzle fénnyel az 1889-es világkiállításra készült hatalmas épület, amit puzzle elemekből tudsz összeállítani. A mozaikdarabok könnyen és pontosan csatlakoznak egymáshoz, az alapzat LED fénnyel van felszerelve, ami akár több, váltakozó színekkel is képes világítani. A játék 3 darab AAA mikro ceruzaelemmel működik, a csomagolás az elemeket nem tartalmazza. Az Eiffel-torony 216 darabos 3D puzzle fénnyel összerakott magassága: 47 cm, az alap méretei: 18 X18 cm.",
        kedvelt: true,
    },
    {
        nev: "Dino Mini puzzle 54 db Disney mesék",
        kep: "../Pictures/Jatekfegyverek/frozenPuzli.png",
        id: 60,
        ar: 795,
        leiras: "Walt Disney állatfiguráit, vagy hercegnőit szereted jobban? A Disney mini 54 darabos puzzle készletek között megtalálod a kedvenced! A kirakós Disney hercegnők, Verdák, Micimackó és Mikiegér változatban rendelhető, erős kartonból készültek, élénk színekkel. Kirakott méretek: 19 x 13 cm. A játékok külön kaphatóak. A megjegyzésben kérjük tüntesd fel, hogy melyik változatot szeretnéd.",
        kedvelt: false,
    },
    {
        nev: "Ravensburger Puzzle 2000 db Brooklynból Manhattenbe",
        kep: "../Pictures/Jatekfegyverek/hidPuzzle.png",
        id: 61,
        ar: 11995,
        leiras: "Ismerd meg New York legismertebb hídját a puzzle kirakásával! A Puzzle 2000 db - Brooklynból Manhattenbe készletért ódáig lesz minden utazni vágyó! A 2000 darabból álló puzzle a Brooklyn hidat ábrázolja naplementében. Keltsd életre a képet otthonodban és rakd ki a puzzle-t! Az izgalmas játékot a család összes tagja élvezni fogja. Keressétek meg az összeillő párokat és pattintsátok össze őket! A kép elkészítése közben fejlődik a koncentrációs képességetek és a logikus gondolkodásotok is. Mindegy egyes elem összeállításával közelebb kerültök a kép elkészítéséhez! Kellemes időtöltés lesz a New York-i látkép elkészítése, miközben sokat nevet együtt a család. Az elkészített műalkotást kitehetitek otthonotok díszéül, így mindig jó élményeket fog okozni, ha rá néztek. A készlet tartalmazza a 2000 db-os puzzle-t, mely a Brooklyn hidat ábrázolja. A színpompás játék összeállítását 10 éves kortól ajánljuk.",
        kedvelt: false,
    },
    {
        nev: "Ravensburger Puzzle 500 db Harry Potter Roxfortban",
        kep: "../Pictures/Jatekfegyverek/HarryPotta.png",
        id: 62,
        ar: 4995,
        leiras: "Kedvenc Harry Potter sorozatod szereplőit rakhatod ki ezzel az 500 darabos kirakóval. A Ravensburger® már 1891 óta gyártja puzzle képkirakó termékeit. A több, mint 120 éves gyártói tapasztalat és a fokozott figyelem, amit a részletekre fordítanak, garantálja a minőséget. Puzzle képeik, az általuk kizárólagosan kifejlesztett, extra vastag, vászon strukturált kartonpapírból készülnek. A vágószerszámok gondos tervezése és kézzel történő kialakítása garantálja a tökéletes illeszkedést és azt, hogy nincs két egyforma puzzle darab.",
        kedvelt: false,
    },
    {
        nev: "Dino Puzzle 24 db - Peppa malac",
        kep: "../Pictures/Jatekfegyverek/PeppaPuzzle.png",
        id: 63,
        ar: 1995,
        leiras: "A játszóházba igyekvő Peppa malac, mozaikdarabokból kirakható képen! A Peppa malac 24 darabos puzzle George, Nagymami malac és Peppa malac képét ábrázolja, ahogy a kertben, egy játszóház előtt szórakoznak. A kirkaós kicsi kezekhez készült, a mozaikdarabok pontosan illeszkednek egymáshoz. A Peppa malac 24 darabos puzzle kirakott méretei: 26 x 18 cm.",
        kedvelt: false,
    },
    {
        nev: "Clementoni: 150 db-os puzzle Monster High Draculaura",
        kep: "../Pictures/Jatekfegyverek/clementoni.png",
        id: 64,
        ar: 2995,
        leiras: "A Monster High Draculaura puzzle egy izgalmas és színes kirakó, amely 150 darabból áll, és a népszerű Monster High sorozat egyik kedvelt karakterét, Draculaurát ábrázolja. A kirakós játék kiváló minőségű, és a Clementoni által gyártott, garantálva a tartósságot és a részletek éles megjelenését",
        kedvelt: false,
    },
]
// MŰANYAGJÁTÉK VÉGE
let airsoftFegyverek = [
    {
        nev: "Specna Arms Airsoft Sniper SA-S02 CORE",
        kep: "../Pictures/AirsoftFegyverek/sa-s02.png",
        id: 65,
        ar: 2995,
        leiras: "Legyél te a vízicsaték királya ezzel az 50 centiméteres vízipisztollyal. A pisztoly garantálja a fergeteges szórakozást a nyári napokon. Magaddal viheted a strandra, a tengerpartra, de akár egy nyári szülinapi partinak is mókás kiegészítője lehet. Csak töltsd meg a tartályt vízzel és már indulhat is a játék.",
        kedvelt: true,
    },
]