let tarsasJatek = [
    {
        nev: "Fedőnevek",
        kep: "../Pictures/Tarsas/fedonevek.png",
        id: 1,
        ar: 4500,
        leiras: "A Fedőnevek egy nagyon könnyen tanulható társasjáték, 2 - 8 játékos részére, az átlagos játékidő rövid, csak 15 perc. A játékot az Év Játékának választották 2016-ban (Spiel des Jahres) és jelölték is 2015-ben (BGG), illetve 2015-ben több, összesen 3 másik elismerést és jelölést is kapott. A társast, a könnyebb tanulhatósága ellenére, csak 14 éves kortól ajánljuk kipróbálni. A játékmenet erősen épít a szövetségek, a memória, a merj és nyerj és a limitált kommunikáció mechanizmusokra.",
        kedvelt: false
    },
    {
        nev: "Csordaszellem",
        kep: "../Pictures/Tarsas/csordaSzellem.png",
        id: 2,
        ar: 9000,
        leiras: "Köszöntünk a Csordaszellem világában! Ez nem csak egy sima társasjáték: ez egy izgalmas kaland, ahol a családod, barátaid és még a tehéncsordák is összegyűlnek a nagy összecsapásra.",
        kedvelt: true
    },
    {
        nev: "Dixit",
        kep: "../Pictures/Tarsas/dixit.png",
        id: 3,
        ar: 10000,
        leiras: "A határtalan képzelet játéka! A Dixit egy gyönyörűen illusztrált asszociációs játék, amellyel fantáziánkat szabadon engedve, újabb és újabb történeteket szőhetünk. Mindenki kap a kezébe hat darab nagyméretű kártyát, rajtuk festményekkel. A kezdőjátékos kiválaszt a kezében levők közül egyet, kitalál  hozzá egy mondatot, amely a képre jellemző, de mégsem túl  nyilvánvaló. Mindenki más is kiválaszt egy képet a kezéből, amelyre szerinte illik az adott mondat. Majd felfedjük  a lapokat, és a mesélőn kívül mindenki szavazhat, hogy  melyik képet választotta a mesélő. A Dixit egyike a legkedvelebb, legszórakoztatóbb társasjátékoknak, számtalan nemzetközi díj nyertese. Világszerte 1,5 milliónál is több példányt vásároltak belőle, ami nem lehet véletlen. Véleményünk szerint is az egyik legjobb társasjáték családok, baráti társaságok számára, de iskolák és más gyermekintézmények is gyakran választják készségfejlesztő és akár terápiás célokra.",
        kedvelt: false,
    },
    {
        nev: "Imagine",
        kep: "../Pictures/Tarsas/imagine.png",
        id: 4,
        ar: 7670,
        leiras: "Az Imagine egy zseniális ötleten alapuló, kreatív társasjáték. Engedd szabadjára a fantáziád: használj fel annyit és úgy a 60 átlátszó kártyából, hogy a többiek minél előbb kitalálják a helyes megoldást (filmek, helyek, szereplők...)! A kártyákat kedved szerint összeillesztheted, egymásra rakhatod, variálhatod és mozgathatod. Keltsd őket életre, és segíts a játékostársaidnak kitalálni, hogy mire gondolsz! A lehetőségek száma végtelen! Tedd próbára magad, nincsenek korlátok!",
        kedvelt: true,
    },
    {
        nev: "Truth or Drink",
        kep: "../Pictures/Tarsas/truthOrDrink.png",
        id: 5,
        ar: 7600,
        leiras: "Ismerd meg a Truth or Drink társasjátékot! Te döntesz: vagy bevallod a csupasz igazságot, vagy iszol egyet... de csak tisztán! Ez a játék garantálja, hogy az este végére szorosabbá válnak a barátságok, hiszen olyan titkok kerülnek napfényre, amelyekről korábban még csak nem is álmodtál.", 
        kedvelt: false,
    },
    {
        nev: "Bűnügyi krónikák",
        kep: "../Pictures/Tarsas/bunugyiKronikak.png",
        id: 6,
        ar: 14560,
        leiras: "Kedves Játékos! London, napjainkban. Gondterhelten lépsz ki a főnök irodájából az őrsön. Egy holttestet találtak a Hyde Parkban, és a kapitány neked adta az ügyet. Nem ez lesz az első nyomozásod, valahogy mégis rossz előérzeted támad az üggyel kapcsolatban... Lerázod magadról a baljós hangulatot, beszállsz a kocsiba, és elindulsz a tett helyszínére.",
        kedvelt: false,
    },
    {
        nev: "Az őszinteség játéka",
        kep: "../Pictures/Tarsas/ozintesegJateka.png",
        id: 7,
        ar: 8540,
        leiras: "A Körvonal kártyajáték egy remek módja annak, hogy jobban megismerjük egymást és önmagunkat. Nincsenek jó vagy rossz válaszok, csak az őszinteség és a közös beszélgetés a fontos. Legalább ketten játszható, de előfordulhat, hogy egy idő után már csak beszélgetünk, mert annyira jól érezzük magunkat.",
        kedvelt: false,
    },
    {
        nev: "Activity Original",
        kep: "../Pictures/Tarsas/activityOriginal.png",
        id: 8,
        ar: 13570,
        leiras: "Az Activity Original társasjáték a Piatniktól pontosan ezért jött létre. Ez a játék, ahol mindenki nyertes – kivéve, aki nem vesz részt benne! Úgyhogy csatlakozz te is a szórakozásra vágyók táborához és fedezd fel, hogy a nevetés valóban a legjobb gyógymód.",
        kedvelt: false, 
    },
    {
        nev: "Activity Felnőtt",
        kep: "../Pictures/Tarsas/activityFelnott.png",
        id: 9,
        ar: 17650,
        leiras: "Megújult szabályok, új erotikus feladványok és szleng kifejezések! Izgalmat fokozó időmérő és érdekes játékfelület! élre a gátlásokkal Hölgyek, Urak és máris indulhat az Activity sikerjáték, erotikus feladványokkal tűzdelt változata, hogy csúcsára érjen a bulin a hangulat!",
        kedvelt: true,
    },
    {
        nev: "Elvarázsolt Labirintus",
        kep: "../Pictures/Tarsas/elvarazsoltLabirintus.png",
        id: 10,
        ar: 9999,
        leiras: "Nagycsoportos ovis gyerekeknek tervezett sikerjáték Dirk Baumanntól, mely 2009-ben Az Év Gyerekjátéka díjat is elnyerte. Kis varázslótanoncokként próbáljuk összegyűjteni a varázstárgyakat egy különleges, elvarázsolt labirintusban. Nemcsak szerencse, hanem jó memória is szükséges a győzelemhez, ugyanis az útvesztő falai láthatatlanok! A kétrétegű játéktábla alsó felén variálható labirintusrendszert építhetünk falapocskákból. A mágneses bábuk alsó részéhez fémgolyó illeszkedik, mely a követi a bábu mozgását, míg falba nem ütközik. Aki nyerni akar, annak bizony meg kell jegyeznie, hogy hol vannak a labirintus falai.",
        kedvelt: false
    },
    {
        nev: "Légi társaság",
        kep: "../Pictures/Tarsas/legiTarsasag.png",
        id: 11,
        ar: 7999,
        leiras: "Vezérleld az utasszállító repülőgépet a megbízható társaddal, tökéletesen hangolva az erőfeszítéseket, és szállítsátok le az utasokat a világ minden táján. Csak egy kis együttműködésre és acélidegekre van szükség a sikerhez. bben a kooperatív társasjátékban egy csapatként, pilótákat alakítva kell a világ különböző repülőterein landolnotok. De egy repülőgéppel leszállni korántsem olyan egyszerű feladat, mint ahogyan azt elsőre gondolnánk. Kommunikálnotok kell az irányítótoronnyal, hogy megbizonyosodjatok róla, hogy biztonságosan megközelíthetitek a leszállópályát. Az előkészületek nagyon fontosak: az összes elemet el kell távolítani a vezérlőpultból és össze kell ragasztani a kétoldalas ragasztólapokat a vezérlőpult belsejében és hátulján. Rakhatsz a fordulásjelző-korong helyére és a kapcsolókat a zöld lámpákra.",
        kedvelt: false,
    },
    {
        nev: "Kuruzsló és Tsa. - Quedlinburgi Futam",
        kep: "../Pictures/Tarsas/quedlinburgiFutam.png",
        id: 12,
        ar: 5890,
        leiras: "A verseny napja van Quedlinburgban, és az ételek és a szerencse megfelelő kombinációjával győzelemre lovagolhatsz a lovaddal, és elnyerheted az arany üstöt. A Kuruzsló és Tsa. - Quedlinburgi Futam hasonló játékmenettel rendelkezik, mint a Kuruzslók Quedlinburgban a játék során minden játékos saját zsetonzsákot épít, majd ezeket a zsetonokat húzza, hogy megpróbáljon továbbjutni a győzelemhez.",
        kedvelt: false,
    },
    {
        nev: "Mycelia",
        kep: "../Pictures/Tarsas/mycelia.png",
        id: 13,
        ar: 16990,
        leiras: "Az avarban, ahová az ember tekintete gyakran nem ér el, a gombák királysága virágzik. Kapcsolódj be te is ebbe az örök körforgásba, légy részese a mindent összekötő hálózatnak – ki tudod használni a gombáid adta minden erőt, hogy magad mögé utasítsd az ellenfeleidet ebben a kíméletlen versenyben? A Mycelia egy dinamikus taktikai játék, amelyben a gombakirályságod létrehozásáért és területért folytatott versenyben vehetsz részt. A játék követi a gombák életciklusát: teremtés, terjeszkedés, pusztulás és újjászületés. A játék során pontokat gyűjtesz gombák növesztésével, spórákat szórsz szét a hálózatod bővítéséhez, és a gombák elpusztulásával különleges akciókat oldasz fel.",
        kedvelt: true,
    },
    {
        nev: "A sárkánybarlang rejtélye",
        kep: "../Pictures/Tarsas/sarkanyBarlangRejtelye.png",
        id: 14,
        ar: 6000,
        leiras: "Fedezd fel a sárkányok elrejtett kincseit, de vigyázz, nehogy a pókok hálójába ess! Most nagyon csendben kell lennetek, ha ép bőrrel meg akarjátok úszni a kalandot a sárkány barlangjába! Apró lépésekkel haladtok és igyekeztek gyémántot és különböző kincseket begyűjteni. De emlékeztek rá, hogy mit merre láttatok? Legyetek bátrak, kaparintsátok meg a kincseket, és a dicsőség nem marad el! Ha szeretnél egy izgalmas, kalandokkal teli játékot, amit az egész család élvezhet, akkor ne habozz! Szerezd be most A sárkánybarlang rejtélye társasjátékot, és kezdődhet a kaland!",
        kedvelt: true,
    },
    {
        nev: "Hygge",
        kep: "../Pictures/Tarsas/hygge.png",
        id: 15,
        ar: 3590,
        leiras: "Itt az ideje a téli álomnak, de a lakásodra ráfér egy kis munka, hogy igazán tökéletes legyen a nagy hidegre. Válogass okosan, kérd meg a megfelelő állatokat, hogy segítsenek, és garantáltan Tiéd lesz a legkellemesebb kis odú széles e vidéken. Ma buli van! De mindenki cucca szanaszét hever a házban, így mielőtt megérkeznének a vendégek, rendet kell rakni. Nagyi és Nagypapa is besegít, de a vendégek bármikor betoppanhatnak. Próbálj meg gyorsabban rendet rakni, mint bárki más. Tud minden családtag rendet rakni és fogadni a vendégeket baleset nélkül?",
        kedvelt: false,
    },
    {
        nev: "Melyik történetből jöttem?",
        kep: "../Pictures/Tarsas/melyikTortenetbolJottem.png",
        id: 16,
        ar: 5400,
        leiras: "Képes vagy felismerni, melyik bibliai történetre utalunk? Játssz activity-stílusban, mutogatva vagy akár szavak nélkül mesélve! Vajon újra tudod építeni a történetet a kulcsszavak alapján? Megtalálod-e a Biblia lapjain a történet nyomait? Ez a játék próbára teszi a tudásod és kreativitásod, ahogy a szónyomok alapján megpróbálod kitalálni az eredeti történetet. A játék 144 kártyát tartalmaz, melyekből 72 az ószövetségi, 72 pedig az újszövetségi történetekhez kapcsolódik. Minden kártyán 9 szó vagy kifejezés található, három különböző nehézségi szint szerint elrendezve. Ezekkel a szavakkal sokféle játékot játszhatsz: kitalálós, történetépítő, történetmesélő és történetnyomozó játékokat. A játék ideális hittanórákra is, hiszen rengeteg javaslatot tartalmaz erre vonatkozóan.",
        kedvelt: false
    },
];
// TÁRSASJÁTÉK VÉGE
let elektronikusJatek = [
    {
        nev: "Little lives pets: Mangó",
        kep: "../Pictures/Elektronikus/interaktivMaki.png",
        id: 17,
        ar: 21999,
        leiras: "Ismerd meg Mangót, a legaranyosabb kis interaktív maki babát, aki hamar a gyerekek legjobb barátjává válik! A Little Live Pets: Mangó, az interaktív maki babám egy igazán szeretnivaló, puha plüssfigura, amely valósághű viselkedésével hódítja meg a szíveket. Mangó több mint 70 különböző hangot és mozdulatot képes produkálni, így igazi társ a játékban. Ha a szájába helyezed az ujjadat, szopizni kezd, és boldogan csücsül az öledben. Emellett etetheted a hozzá tartozó cumisüvegből is, ami után elégedetten gügyög és boldogan mocorog.",
        kedvelt: false,
    },
    {
        nev: "Furby",
        kep: "../Pictures/Elektronikus/furbyInteraktiv.png",
        id: 18,
        ar: 19999,
        leiras: "A népszerű Furby nem csak egy hagyományos plüssfigura, hanem annál sokkal több! A Furby-k mindegyike külön személyiséggel rendelkezik, ennek köszönhetően más és más reakciókat produkálnak. De vajon a Te Furby-d milyen személyiséget sajátít el? Minden azon múlik, hogyan játszol és foglalkozol vele! A kis lila szőrmók minden egyes megmozdulásodra reagál, így akár etetheted, felemelheted, rázhatod, megfordíthatod vagy zenét játszhatsz le neki, mindenre reagálni fog!",
        kedvelt: false,
    },
    {
        nev: "Tamagocsi",
        kep: "../Pictures/Elektronikus/pocketPet.png",
        id: 19,
        ar: 1999,
        leiras: "Ismét hódít a 90-es évek játék szenzációja, a Tamagotchi! Válaszd ki a 168 féle kisállat közül a kedvencedet, majd gondoskodj róla a kis gombok segítségével, etesd meg, játssz vele, altasd el, gyógyítsd meg, ha beteg, takaríts fel utána, de akár le is zárhatod, hogy senki ne nyúlhasson hozzá!",
        kedvelt: true,
    },
    {
        nev: "Verd át a kamerát",
        kep: "../Pictures/Elektronikus/verdAtAKamerat.png",
        id: 20,
        ar: 12999,
        leiras: "A Tomy 'Verd át a kamerát' társasjáték egy izgalmas ügyességi próba, ahol a cél a drágakő megszerzése, miközben egy mozgásérzékelős kamera próbálja elkapni a játékosokat. Egyszerűen helyezze el a dobozban lévő éberszemű kamerát egy asztalon vagy bármilyen más stabil felületen, rejtsd el a kincset, és kezdődhet az izgalom.",
        kedvelt: false,
    },
    {
        nev: "Szuper Mágikus Jinn",
        kep: "../Pictures/Elektronikus/magikusJinn.png",
        id: 21,
        ar: 11995,
        leiras: "Sziasztok! Szuper Mágikus Jinn vagyok!\\\\ Ez a mókás figura mindig így köszön, és bármikor szívesen játszik a gyerekekkel: méghozzá barkochbát. Csak gondolni kell egy állatra, ruhadarabra, zöldségre vagy gyümölcsre, sportágra vagy foglalkozása, Szuper Mágikus Jinn kitalálja azt! Ez az interaktív lényecske eldöntendő kérdéseket tesz fel, hangfelismerő rendszerének köszönhetően pedig a gyerekek szóban válaszolhatnak, így tulajdonképpen beszélgetnek Jinnel. Igen, nem, nem tudom, attól függ... Ahogy megválaszolják a kérdéseket, Jinn egyre közelebb kerül a megfejtéshez. Remekül leköti a már nagyobb óvodás gyerekeket - sőt, akár a szülőket - is, kompakt mérete miatt pedig utazáshoz is ideális társ. A játék remekül fejleszti a logikus gondolkodást, miközben a gyerekek jól szórakoznak.",
        kedvelt: true,
    },
    {
        nev: "Bitzee",
        kep: "../Pictures/Elektronikus/bitzeeInteraktiv.png",
        id: 22,
        ar: 19990,
        leiras: "Fedezd fel a Disney varázslatos világát a Bitzee Interaktív digitális állat Disney kiadással! Ez az innovatív játék a klasszikus tamagotchi élményt ötvözi a legújabb technológiával, hogy a gyermeked elmerülhessen a Disney karakterek gondozásában és játékában. A Bitzee egy kicsi, hordozható eszköz, melyben 30 különböző Disney karaktert lehet felfedezni, beleértve Mickey egér, Minnie egér, és még sok más népszerű figurát. A gyerekeknek lehetőségük van etetni, gondozni, és játszani ezekkel a digitális barátokkal, miközben különböző kihívásokat és játékokat oldanak meg. A színes kijelző és az interaktív funkciók révén a Bitzee minden pillanatban új élményeket kínál, a gyermekek figyelmét lekötve és kreativitásukat fejlesztve.",
        kedvelt: false,
    },
    {
        nev: "Tacsi robotkutya",
        kep: "../Pictures/Elektronikus/robotKutya.png",
        id: 23,
        ar: 34999,
        leiras: "A kutya az ember legjobb barátja, különösen ha ez a kutya egy robot, hiszen akkor biztos, hogy a gazdi minden parancsát teljesíti! A Tacsi kutyus nagyon cuki, szófogadó és sokat szeret játszani, így ideális játszópajtása lesz a gyerekeknek. Mindenhova követi őket és figyeli minden apró mozdulatukat. Tacsi hangokat képes kiadni, csóválja a farkát vagy épp szaglászik valami után akárcsak egy igazi kutya, de természetesen különféle trükköket is előadhattok közösen. A labdájával lehet irányítani, kétféle funkciót kiválasztva. A követő módban az árnyékok és mozgások segítségével tájékozódik, mint egy valódi kutyus, míg a kézi vezérlés módot bekapcsolva pedig a labdán lévő gombok segítségével lehet vezérelni.",
        kedvelt: true,
    },
    {
        nev: "Táncoló kaktusz",
        kep: "../Pictures/Elektronikus/tancoloKaktusz.png",
        id: 24,
        ar: 10999,
        leiras: "A legtöbb gyerekszobában nem igen vannak növények, hiszen a rendszeres locsolás elmaradása nem tesz túl jót nekik, de most itt a nagyszerű lehetőség, hogy egy mókás kaktusz azért helyet kapjon a polcon vagy éppen az íróasztal egyik sarkán. Ez a kaktusz nem éppen hétköznapi figura, hiszen a benne rejlő elektronikának és a három darab AAA ceruzaelemnek köszönhetően mókás zenével és vicces tánccal tudja szórakoztatni a gyerekeket, ráadásul attól sem kell félni, hogy bárkit megszúrna, hiszen ez egy igazán kedves kaktusz.",
        kedvelt: false,
    },
    {
        nev: "LG Kizon W105",
        kep: "../Pictures/Elektronikus/kizon.png",
        id: 25,
        ar: 4999,
        leiras: "Az LG KizON okoskarpánt GPS és csak a helymeghatározás céljából működő WiFi segítségével mindig segít tájékozódni gyermeke pontos tartózkodási helyéről. A karpánt segítségével, gyermeke egyetlen gombnyomással bármikor aktiválni tud egy előre betáplált telefonszámot. Abban az esetben, ha gyermeke nem reagál a hívásra, egy bizonyos idő után automatikusan aktiválódik a készülék beépített mikrofonja. Ezáltal hallható lesz gyermeke hangja és a környezet zaja.",
        kedvelt: false,
    },
    {
        nev: "ZR Walkie Talkie",
        kep: "../Pictures/Elektronikus/walkieTalkie.png",
        id: 26,
        ar: 4499,
        leiras: "Ez a vagány kültéri Walkie Talkie antennával ideális választás a fiatal felfedezők számára. A menő burkolattal ellátott készülékkel a gyerekek jócskán eltávolodhatnak egymástól, hiszen a készülék több méteres hatótávolsággal is képes működni a szabadban. Használat közben nem szabad elfelejteni, hogy el azonos sávon kell használni mindkét készüléket, és ennék a készüléknél is igaz, hogy vagy beszélünk vagy hallgatunk, így amikor végeztél a mondandóddal ne felejtsük el azt mondani, hogy VÉTEL!! ",
        kedvelt: false,
    },
    {
        nev: "Star Wars Lightsaber Forge: Darksaber",
        kep: "../Pictures/Elektronikus/fenykard.png",
        id: 27,
        ar: 9999,
        leiras: "A Star Wars Lightsaber Forge: Darksaber kinyitható elektronikus fénykard tökéletes választás a Star Wars világának rajongói számára, akik szeretnék a Mandalori örökség egyik legikonikusabb fegyverét a kezükben tartani. A Darksaber nemcsak egy fénykard, hanem a galaxis egyik legkülönlegesebb, fekete pengéjű fegyvere, amelyet Mandalore uralkodói használtak. Most te is csatlakozhatsz ehhez a legendás hagyományhoz ezzel a valósághű fény- és hanghatásokkal felszerelt játékkal.",
        kedvelt: true,
    },
    {
        nev: "Óriás zongora",
        kep: "../Pictures/Elektronikus/zongora.png",
        id: 28,
        ar: 17999,
        leiras: "Játszd el kedvenc zenéidet a hatalamas méretű zongorán! A Zongora óriás játszószőnyeg egy nyomásérzékelős billentyűzet, két oktávval. A zongorán lépkedve tudsz játszani, a játék 8 hangszer hangját tudja utánozni, négy beépített dalt is le tud játszani. A szőnyeg hangereje állítható, a művedet fel tudod vele venni, és vissza is tudod hallgatni! A Zongora óriás játszószőnyeg 4 darab AA ceruzaelemmel működik, a csomagolás az elemeket nem tartalmazza.",
        kedvelt: false,
    },
    {
        nev: "Játék mobiltelefon",
        kep: "../Pictures/Elektronikus/jatekTelefon.png",
        id: 29,
        ar: 1999,
        leiras: "Gyakorold a telefonálást a szétcsúsztatható játéktelefonnal! A Játék mobiltelefon egy élethű mobiltelefon, ami fejleszti a kommunikációs készséget. A telefon fedőlapja elcsúsztatható, a gombok megnyomására a játék különböző mondatokat, hangokat ad ki magából. A telefon kijelzője hologramos, több irányból nézve más-más kép jelenik meg rajta. A Játék mobiltelefon 2 db LR44 gombelemmel működik, a csomagolás az elemeket tartalmazza. A telefon összecsukott méretei: 10 x 5 x 2 cm. A termék fekete, bordó és világoskék színben kapható. A játékok külön kaphatóak. A megjegyzésben kérjük tüntesd fel, hogy melyik változatot szeretnéd!",
        kedvelt: false,
    },
    {
        nev: "Első laptopom",
        kep: "../Pictures/Elektronikus/elsoLaptopom.png",
        id: 30,
        ar: 8799,
        leiras: "Nyiss kaput a szórakoztatásra! A gyermeklaptopunkban 33 különböző tevékenységet találsz. Tanulhatod a betűket, a számokat és a szavakat, valamint zenélhetsz és játékokkal játszhatsz. Imádni fogod, ahogy az egérrel mozoghatsz a képernyőn. Pont olyan, mint az igazi! 3 éves kortól ajánlott. Hat választható működési mód. Olvasási-írási készségek. Problémamegoldás. Próbálj ki! Kezelési útmutató: Tisztítás csak törléssel.",
        kedvelt: true,
    },
    {
        nev: "Bobby kutyus",
        kep: "../Pictures/Elektronikus/bobbyKutyus.png",
        id: 31,
        ar: 7999,
        leiras: "Minden gyerek életében eljön a pillanat amikor bejelentik: \"Anyaaaa, úúúúgy szeretnék egy kutyát!\" A felelős állattartásra fel kell készíteni a gyerekeket, ez a sétáltatható plüss kiskutya pedig nagyszerű első lépés az óvodáskorú gyerekek számára, hiszen megtanulhatják, hogyan kell gondoskodni egy igazi állatról. A kutyus szuper cuki, és különböző funkciókkal is rendelkezik. Csak fel kell tolni a pórázon található pöcköt, hogy az eb ugatni kezdjen és csóválja a farkát séta közben.",
        kedvelt: false,
    },
    {
        nev: "Dance Revolution Táncszönyeg",
        kep: "../Pictures/Elektronikus/tancSzonyeg.png",
        id: 32,
        ar: 9990,
        leiras: "Most lehet csak igazán jót táncolni és ugrálni, ideje megmutatni, ki mit tud! A Dance Revolution táncszőnyeg TV-re és PC-re csatlakoztatható, és egy igazán remek szórakozás a gyerekeknek! A hiperaktív gyerkőcök kedvükre mozoghatnak, miközben fejlődnek a reflexeik és a ritmusérzékük. Az ifjú táncosoknak a TV-n vagy a számítógép monitorán megjelenő nyilakat követve kell megismételniük a lépéseket. Akinek több helyes lépése lesz, az nyeri a nagy táncpárbajt. A gyerekek összesen 48 dal és 2 játék közül választhatnak.A táncszőnyeg TV-hez RCA csatlakozóval, PC-re USB csatlakozóval köthető. A táncszőnyeg kizárólag az RCA (kompozit A/V) csatlakozóval rendelkező TV-re köthető. A táncszőnyeg működése nem igényel külön elemeket.A csomagolás tartalmaz egy táncszőnyeget, egy CD-t, a csatlakoztatáshoz szükséges kábeleket, valamint egy adaptert.",
        kedvelt: false,
    },
];
// ELEKTRONIKUSJÁTÉK VÉGE
